name: CD

on:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install && cd dist/vscode-extension && npm install

    - name: Build extension
      run: cd dist/vscode-extension && npm run build

    - name: Package extension
      run: cd dist/vscode-extension && npm run package && vsce ls --tree

    - name: Create build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: extension-files
        path: dist/vscode-extension/

  publish-extension:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: extension-files
          path: .

      - name: Publish extension
        run: |
          npm install -g @vscode/vsce
          vsce publish --pat ${{ secrets.VSCODE_TOKEN }} || true
